"""FR/EN label dictionaries shared by every open report.

Each report defines its own labels as a structured dict (see
reports/open/executive_snapshot.py and model_release_benchmark.py) rather
than writing a report once and machine-translating the rendered HTML
afterwards (the approach the private Euria generator uses). Structured
labels keep FR and EN both first-class and let future languages be added
without touching the render logic.
"""

from __future__ import annotations

SUPPORTED_LANGUAGES = ("fr", "en")


def require_language(lang: str) -> str:
    if lang not in SUPPORTED_LANGUAGES:
        raise ValueError(f"Unsupported language {lang!r}. Supported: {SUPPORTED_LANGUAGES}.")
    return lang


COMMON = {
    "en": {
        "generated": "Generated",
        "campaign_id": "Campaign ID",
        "dataset": "Dataset",
        "arms_tested": "Providers / models tested",
        "repetitions": "Repetitions per prompt",
        "observations": "Observations",
        "errors": "Execution errors",
        "measurement_schema_versions": "Measurement schema version(s)",
        "measurement_engine_versions": "Measurement engine version(s)",
        "simulated_notice": "This campaign used the offline Periscope simulator, not live NeoMundi measurements. Synthetic data -- for demonstration only.",
        "boundary_title": "Measured signal, not a verdict.",
        "boundary_text": (
            "This document summarizes signals observed during this campaign. "
            "It is not a factual verdict, a safety certification, a compliance "
            "conclusion, or a universal ranking of models. Results apply only "
            "to the documented corpus, provider(s), model(s), repetitions, "
            "measurement version(s) and time period."
        ),
        "footer_engine": "Generated by NeoMundi AI Periscope",
        "na": "n/a",
    },
    "fr": {
        "generated": "Généré",
        "campaign_id": "ID de campagne",
        "dataset": "Dataset",
        "arms_tested": "Providers / modèles testés",
        "repetitions": "Répétitions par prompt",
        "observations": "Observations",
        "errors": "Erreurs d'exécution",
        "measurement_schema_versions": "Version(s) de schéma de mesure",
        "measurement_engine_versions": "Version(s) du moteur de mesure",
        "simulated_notice": "Cette campagne utilise le simulateur hors-ligne de Periscope, pas des mesures NeoMundi réelles. Données synthétiques -- à but de démonstration uniquement.",
        "boundary_title": "Signal mesuré, pas verdict.",
        "boundary_text": (
            "Ce document résume des signaux observés pendant cette campagne. "
            "Il ne constitue ni un verdict factuel, ni une certification de "
            "sécurité, ni une conclusion de conformité, ni un classement "
            "universel des modèles. Les résultats valent uniquement pour le "
            "corpus, le(s) provider(s), le(s) modèle(s), les répétitions, "
            "la (les) version(s) de mesure et la période documentés."
        ),
        "footer_engine": "Généré par NeoMundi AI Periscope",
        "na": "n.d.",
    },
}


def t(lang: str, key: str) -> str:
    require_language(lang)
    return COMMON[lang].get(key, key)
